### ISSUE TITLE
Is there any way to pass  Applicant ID through JS code in android? same as IOS? 

### ISSUE THREAD

**Issue by yoginair** [onfido/onfido-sdk-react-native-sample-app#10]
As in below code there is a way to pass applicant ID but in android? 
```
  launchSDK() {
    if (Platform.OS == 'android') {
      NativeModules.OnfidoSDK.startSDK(
        (applicantId) => { this.setTextContent("Verification complete", "To perform another verification, press \"Launch\"") },
        (errorCause) => { this.setTextContent("Flow not finished", "To try again, press \"Launch\"") }
      );
    } else {
      NativeModules.OnfidoSDK.startSDK(
        'APPLICATION_ID',
        (applicationId) => { this.setTextContent("Verification complete", "To perform another verification, press \"Launch\"") },
        (errorCause) => { this.setTextContent("Flow not finished", "To try again, press \"Launch\"") }
      );
    }
  }
```

**Comment by AbhishekCode** [comment]
@yoginair ???

**Comment by yoginair** [comment]
@AbhishekCode didn't get any update from their side

**Comment by anuragajwani** [comment]
@yoginair you can create applicant ids on the Android SDK too https://github.com/onfido/onfido-android-sdk#5-creating-the-sdk-configuration.

Hope that helps

**Comment by sergiomarqmoura** [comment]
@yoginair @AbhishekCode you can indeed pass the applicant ID to the SDK by using the `withApplicant(applicantId)` method.
Let us know if it works for you

**Comment by anuragajwani** [comment]
@yoginair @AbhishekCode we have updated the react native sample app using our latest sdks and latest build tools. Android integration code now showcases `withApplicant(applincantId)`
