### ISSUE TITLE
removing screen from onfido sdk

### ISSUE THREAD

**Issue by aleksbgs** [onfido/onfido-sdk-react-native-sample-app#12]
![screen shot 2019-02-25 at 5 45 30 pm](https://user-images.githubusercontent.com/274019/53353677-8df92780-3925-11e9-81dd-e128e72beb55.png)
Hi can i remove somehow this screen in my task company want to remove that

**Comment by sergiomarqmoura** [comment]
Hi @aleksbgs . Please refer to our native SDK documentation [documentation](https://github.com/onfido/onfido-android-sdk#customising-sdk) for more details on how to customise your Onfido flow.
