### ISSUE TITLE
Support for the experimental syntax 'nullishCoalescingOperator' isn't currently enabled

### ISSUE THREAD

**Issue by ncuthbert** [onfido/onfido-sdk-react-native-sample-app#13]
I am getting the following error when I try to run on an iOS simulator. 

I tried adding @babel/plugin-proposal-nullish-coalescing-operator to the plugins section of the babel config, but did not work.

Assistance getting this resolved would be appreciated.

> error: bundling failed: SyntaxError: /onfido-sdk-react-native-sample-app-master/node_modules/react-native/node_modules/react-native/Libraries/LayoutAnimation/LayoutAnimation.js: Support for the experimental syntax 'nullishCoalescingOperator' isn't currently enabled (47:23):
> 
>   45 |   UIManager.configureNextLayoutAnimation(
>   46 |     config,
> > 47 |     onAnimationDidEnd ?? function() {},
>      |                       ^
>   48 |     function() {
>   49 |       /* unused */
>   50 |     },
> 
> Add @babel/plugin-proposal-nullish-coalescing-operator (https://git.io/vb4Se) to the 'plugins' section of your Babel config to enable transformation.
>     at Object.raise (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:3831:17)
>     at Object.expectPlugin (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:5148:18)
>     at Object.parseExprOp (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:5763:16)
>     at Object.parseExprOps (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:5739:17)
>     at Object.parseMaybeConditional (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:5702:23)
>     at Object.parseMaybeAssign (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:5647:21)
>     at Object.parseMaybeAssign (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:2621:18)
>     at Object.parseExprListItem (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:6940:18)
>     at Object.parseCallExpressionArguments (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:6070:22)
>     at Object.parseSubscript (/onfido-sdk-react-native-sample-app-master/node_modules/@babel/parser/lib/index.js:5965:29)

**Comment by ncuthbert** [comment]
After hours wasted trying to get this to work, of course it resolves itself 1 min after submitting this issue. I suspect my packager was not running from the correct folder. Not sure how or why.

**Comment by AbhiShrek** [comment]
I am also having this problem, but even after spending an hour it didn't resolve itself. How can i make sure that the package manager is running from correct folder ? ( I want to open this issue again, may be after 1 min of opening the issue, it will resolve )
