### ISSUE TITLE
where is the react-native lib npm package

### ISSUE THREAD

**Issue by jamesjara** [onfido/onfido-sdk-react-native-sample-app#27]
hi guys, I'm a bit confused by reading the package I can't see the library reference onfido, thanks for clarification

**Comment by Bardiamist** [comment]
Seems they not provided it and we should use native code from this repo.

iOS:
[OnfidoSDK.swift](https://github.com/onfido/onfido-sdk-react-native-sample-app/blob/master/ios/ReactNativeSampleApp/OnfidoSDK.swift) (but I'll try to rewrite it on Objective-C for exlude [bridge](https://github.com/onfido/onfido-sdk-react-native-sample-app/blob/master/ios/ReactNativeSampleApp-Bridging-Header.h) and `use_frameworks!`)
[OnfidoSDK.m](https://github.com/onfido/onfido-sdk-react-native-sample-app/blob/master/ios/ReactNativeSampleApp/OnfidoSDK.m)

Android:
[OnfidoSDK.java](https://github.com/onfido/onfido-sdk-react-native-sample-app/blob/master/android/app/src/main/java/com/reactnativesampleapp/OnfidoSDK.java) (I'll call it `OnfidoSDKModule`)
[AppPackage.java](https://github.com/onfido/onfido-sdk-react-native-sample-app/blob/master/android/app/src/main/java/com/reactnativesampleapp/AppPackage.java) (I'll call it `OnfidoSDKPackage`)

It's a pity that there is no official wrapper ready to use.

**Comment by jamesjara** [comment]
yep,  there is one now  (by me, :P) 
```yarn add react-native-onfido```
