### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by ptfly** [onfido/onfido-sdk-react-native-sample-app#6]
I'm trying to build the example project but with the latest xcode 10, it wont let me:
`Module compiled with Swift 4.1 cannot be imported by the Swift 4.2.1`

<img width="211" alt="image" src="https://user-images.githubusercontent.com/1925966/49469047-2bedc200-f80f-11e8-926d-6a9473d9911c.png">

**Comment by anuragajwani** [comment]
Hi @ptfly 

This sample project is using Onfido iOS SDK 7.1.0 which is compatible with Xcode 9.3. We haven't updated this sample project for Xcode 10 compatibility. Try using Xcode 9.3 and running the project. Let me know if the problem persists.

Anurag

**Comment by anuragajwani** [comment]
Hi @ptfly 

The project has now been updated to use the latest Xcode 10.1 and to be Swift 4.2 compatible.

Anurag
