### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by ghost** [onfido/onfido-sdk-react-native-sample-app#7]
Gives me the error:
CFBundleIdentifier", Does Not Exist

Tried deleting the build folder and building it with the legacy build system, but the issue still persists.

**Comment by anuragajwani** [comment]
Hi @danieldelouya 

Have you tried changing the bundle identifier of the Xcode project?

Anurag

**Comment by ghost** [comment]
Yes did that as one of the first things. I’m using Xcode 10, which should be why it’s not working yet, but I really don’t want to downgrade Xcode, so I’m hoping you will update the project soon :)

**Comment by anuragajwani** [comment]
@danieldelouya we have updated the project to use Xcode 10.1. Let me know if you are still encountering problems with the updated sample app

**Comment by lucaspelloni2** [comment]
@anuragajwani 
We are getting the following error (we are using Xcode 10.1 as well). 


![image](https://user-images.githubusercontent.com/17781533/55011691-9016da80-4fe6-11e9-9577-5964c7f61775.png)

Any ideas how to fix this?

**Comment by tbocek** [comment]
Set in your .babelrc your presets:

```
"presets": ["module:metro-react-native-babel-preset"]
```

**Comment by lucaspelloni2** [comment]
Thanks @tbocek
