### ISSUE TITLE
Invalid credentials 

### ISSUE THREAD

**Issue by PeterKow** [onfido/onfido-sdk-react-native-sample-app#8]
I managed to run an Android app but credentials are invalid, can you share some generic credentials?

I contacted sales already, but it might take some time

<img width="457" alt="image" src="https://user-images.githubusercontent.com/10186048/50768750-797ba580-1279-11e9-8f7c-80716bb8d407.png">

Thanks,

**Comment by sergiomarqmoura** [comment]
Hi @PeterKow . Unfortunately for now we don't have any mechanism in place for you to try the SDK without valid credentials. We'll take your request into account though.

**Comment by PeterKow** [comment]
@sergiomarquesmoura so this repo/ app doesn't work, for now. Maybe then you can put this info in `readme` for other devs

I am in contact with your sales team, I guess then I can put my credentials and it should work, or I am missing something else?

**Comment by sergiomarqmoura** [comment]
That's true @PeterKow as soon as you have the credentials you will be able to successfully run it. This repo attempts to showcase how to integrate our mobile SDKs in a react native app, not exactly to showcase the SDK functionality. For that you can checkout our demo apps on the Play Store (https://play.google.com/store/apps/details?id=com.onfido.sdkdemo) and App Store (https://itunes.apple.com/us/app/onfido/id1439589403?mt=8)
